DATABASE_USERNAME=username
DATABASE_PASSWORD=password
DATABASE_URL=jdbc:h2:mem:account_reservation
DATABASE_DRIVER=org.h2.Driver
DDL_AUTO=validate
DATABASE_CHANGELOG=classpath:db/changelog/db-changelog-master.xml

ACTUATOR_BASEPATH=/monitor