server:
  port: 8080

spring:
  datasource:
    driverClassName: ${DATABASE_DRIVER}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show_sql: true
    open-in-view: false
    hibernate.ddl-auto: ${DDL_AUTO}
    properties.hibernate:
      jdbc.time_zone: UTC
      format_sql: true
  liquibase:
    enabled: true
    change-log: ${DATABASE_CHANGELOG}

management:
  server:
    port: 8081
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
  endpoints:
    web:
      base-path: ${ACTUATOR_BASEPATH}
      exposure:
        include: "health,info,threaddump,liquibase,metrics,mappings,beans,env"